test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

cloudflare_r2:
  service: S3
  access_key_id: <%= ENV["R2_CLIENT_ID"] %>
  secret_access_key: <%= ENV["R2_SECRET_KEY"] %>
  endpoint: <%= ENV["R2_S3_ENDPOINT"] %>
  bucket: <%= ENV["R2_BUCKET"] %>
  region: auto
  force_path_style: true
